### ISSUE TITLE
v0.15.30: GSL (https://github.com/ruslo/gsl/) 404

### ISSUE THREAD

**Issue by grisevg** [ruslo/hunter#527]
Hunter fails to load GSL from a non-existent repo.

**Comment by headupinclouds** [comment]
Can you provide more detail on this error, and a small sample that reproduces the issue?

**Comment by grisevg** [comment]
Sorry, of course: 
I only added `hunter_add_package(GSL)` to `CMakeLists.txt` and then ran `cmake` and got the following error appearing over and over:
```
  -- downloading...
         src='https://github.com/ruslo/gsl/archive/v1.16.tar.gz'
         dst='C:/tools/hunter/_Base/Download/GSL/1.16/ce16e45/v1.16.tar.gz'
         timeout='none'
CUSTOMBUILD : error : downloading 'https://github.com/ruslo/gsl/archive/v1.16.tar.gz' failed [C:\tools\hunter\_Base\0a63c66\2e0e6b1\a812237\Build\GSL\Build\GSL-Release.vcxproj]
    status_code: 22
    status_string: "HTTP response code said error"
    log:
    --- LOG BEGIN ---
    timeout on name lookup is not supported
    Trying 192.30.253.112...
  Connected to github.com (192.30.253.112) port 443 (#0)
  schannel: SSL/TLS connection with github.com port 443 (step 1/3)
  schannel: disabled server certificate revocation checks
  schannel: sending initial handshake data: sending 182 bytes...
  schannel: sent initial handshake data: sent 182 bytes
  schannel: SSL/TLS connection with github.com port 443 (step 2/3)
  schannel: failed to receive handshake, need more data
  schannel: SSL/TLS connection with github.com port 443 (step 2/3)
  schannel: encrypted data buffer: offset 1436 length 4096
  schannel: encrypted data length: 1338
  schannel: encrypted data buffer: offset 1338 length 4096
  schannel: received incomplete message, need more data
  schannel: SSL/TLS connection with github.com port 443 (step 2/3)
  -- Retry after 15 seconds (attempt #4) ...
  schannel: encrypted data buffer: offset 3492 length 4096
  schannel: sending next handshake data: sending 126 bytes...
  schannel: SSL/TLS connection with github.com port 443 (step 2/3)
  schannel: encrypted data buffer: offset 51 length 4096
  schannel: SSL/TLS handshake complete
  schannel: SSL/TLS connection with github.com port 443 (step 3/3)
  schannel: incremented credential handle refcount = 1
  schannel: stored credential handle in session cache
  GET /ruslo/gsl/archive/v1.16.tar.gz HTTP/1.1

  Host: github.com

  User-Agent: curl/7.44.0

  Accept: */*



  schannel: client wants to read 16384 bytes
  schannel: encdata_buffer resized 17408
  schannel: encrypted data buffer: offset 0 length 17408
  schannel: encrypted data got 1229
  schannel: encrypted data buffer: offset 1229 length 17408
  schannel: decrypted data length: 1200
  schannel: decrypted data added: 1200
  schannel: decrypted data cached: offset 1200 length 16384
  schannel: encrypted data buffer: offset 0 length 17408
  schannel: decrypted data buffer: offset 1200 length 16384
  schannel: schannel_recv cleanup
  schannel: decrypted data returned 1200
  schannel: decrypted data buffer: offset 0 length 16384
CUSTOMBUILD : The requested URL returned error : 404 Not Found [C:\tools\hunter\_Base\0a63c66\2e0e6b1\a812237\Build\GSL\Build\GSL-Release.vcxproj]
  Closing connection 0
  schannel: shutting down SSL/TLS connection with github.com port 443
  schannel: clear security context handle
  schannel: decremented credential handle refcount = 0

    --- LOG END ---
```
